import { sql } from 'drizzle-orm';
import {
  bigint,
  bigserial,
  boolean,
  index,
  jsonb,
  pgEnum,
  pgTable,
  smallint,
  text,
  timestamp,
  uniqueIndex,
} from 'drizzle-orm/pg-core';
import { users } from './auth';
import { workspaces } from './workspaces';
import { sourceRecords } from './connectors';
import { productProfiles } from './products';
import { reviewItems } from './review';
import { qualifications } from './qualifications';

/**
 * Lifecycle of an outreach draft:
 *
 *   draft       ← freshly generated by the engine, awaiting human review
 *   needs_edit  ← reviewer flagged it for edits but not approved/rejected
 *   approved    ← reviewer signed off; ready for the future Send phase
 *   rejected    ← reviewer rejected; reason captured
 *   superseded  ← a newer draft for the same (review_item, product) replaced
 *                 this one; kept for audit but not surfaced in the queue
 *
 * Phase 8 does NOT send anything — the lifecycle stops at `approved`.
 * The Send phase (later) will read approved drafts and dispatch.
 */
export const outreachDraftStatus = pgEnum('outreach_draft_status', [
  'draft',
  'needs_edit',
  'approved',
  'rejected',
  'superseded',
]);

/**
 * Phase A (staged outreach): every draft belongs to a stage in the
 * sales conversation. The engine picks a different prompt per stage.
 *
 *   discovery  ← first cold email; ≤60 words; asks "who handles X?"
 *                no product pitch
 *   engagement ← in-thread reply driven by the inbound message
 *   pitch      ← only when the recipient explicitly asks for product
 *                detail; full description + research context
 *   closing    ← terminal: thank-you / decline acknowledgement /
 *                handoff confirmation
 *
 * Existing drafts are backfilled to `engagement` since they were
 * generated before staging existed and are mid-conversation.
 */
export const outreachStage = pgEnum('outreach_stage', [
  'discovery',
  'engagement',
  'pitch',
  'closing',
]);
export type OutreachStage = (typeof outreachStage.enumValues)[number];

/**
 * One outreach draft per (review_item, product_profile) attempt. A new
 * draft for the same pair supersedes the previous one — we keep the row
 * but mark it `superseded` so the audit trail is preserved.
 *
 * `method` is the audit trail of how this draft was produced:
 *   - rules: deterministic templates from product profile + lessons
 *   - ai:    AI provider generation
 *   - hybrid: rules-first scaffold, AI fills body
 */
export const outreachDrafts = pgTable(
  'outreach_drafts',
  {
    id: bigserial('id', { mode: 'bigint' }).primaryKey(),
    workspaceId: bigint('workspace_id', { mode: 'bigint' })
      .notNull()
      .references(() => workspaces.id, { onDelete: 'cascade' }),

    // Source linkage. A draft is for a specific review_item and product.
    // We also denormalize sourceRecordId + qualificationId so the draft
    // table can be queried without traversing review_items.
    reviewItemId: bigint('review_item_id', { mode: 'bigint' })
      .notNull()
      .references(() => reviewItems.id, { onDelete: 'cascade' }),
    sourceRecordId: bigint('source_record_id', { mode: 'bigint' })
      .notNull()
      .references(() => sourceRecords.id, { onDelete: 'cascade' }),
    productProfileId: bigint('product_profile_id', { mode: 'bigint' })
      .notNull()
      .references(() => productProfiles.id, { onDelete: 'cascade' }),
    qualificationId: bigint('qualification_id', { mode: 'bigint' }).references(
      () => qualifications.id,
      { onDelete: 'set null' },
    ),

    status: outreachDraftStatus('status').notNull().default('draft'),

    // ---- Phase A: staging ----
    stage: outreachStage('stage').notNull().default('discovery'),
    /** Previous draft in the same conversation (null for stage=discovery). */
    parentDraftId: bigint('parent_draft_id', { mode: 'bigint' }),
    /** Inbound mail_message that prompted this draft (null for cold openers). */
    triggeredByMessageId: bigint('triggered_by_message_id', { mode: 'bigint' }),
    /** Audit chain when the lead was reached via referral(s).
     *  Shape: [{from_email, from_name, at}]. Null for direct outreach. */
    referralChain: jsonb('referral_chain'),

    // ---- generated content ----
    channel: text('channel').notNull().default('email'),
    language: text('language').notNull().default('en'),
    subject: text('subject'),
    body: text('body').notNull(),
    /** Phase 63: operator-reviewed translation of the draft into the
        recipient's language. The send path uses these (when present) instead
        of auto-translating, so the operator can see + tweak the exact
        outgoing text. target_language records which language they're in. */
    subjectTranslated: text('subject_translated'),
    bodyTranslated: text('body_translated'),
    targetLanguage: text('target_language'),
    /** 0..100. Engine self-confidence in the draft. */
    confidence: smallint('confidence').notNull().default(50),

    // ---- generation audit ----
    method: text('method').notNull(), // 'rules' | 'ai' | 'hybrid'
    model: text('model'),
    /** Prompt fragments + lesson IDs + product field snapshots used. */
    evidence: jsonb('evidence').notNull().default(sql`'{}'::jsonb`),
    /** Forbidden phrases that the engine REMOVED before persisting (audit). */
    forbiddenStripped: text('forbidden_stripped')
      .array()
      .notNull()
      .default(sql`'{}'::text[]`),
    /** Lesson IDs whose rule text influenced this draft. */
    matchedLessonIds: bigint('matched_lesson_ids', { mode: 'bigint' })
      .array()
      .notNull()
      .default(sql`'{}'::bigint[]`),

    // ---- review trail ----
    rejectionReason: text('rejection_reason'),
    approvedByUserId: text('approved_by_user_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    approvedAt: timestamp('approved_at', { mode: 'date', withTimezone: true }),
    rejectedByUserId: text('rejected_by_user_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    rejectedAt: timestamp('rejected_at', { mode: 'date', withTimezone: true }),
    editedByUserId: text('edited_by_user_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    editedAt: timestamp('edited_at', { mode: 'date', withTimezone: true }),

    createdBy: text('created_by').references(() => users.id, {
      onDelete: 'set null',
    }),
    createdAt: timestamp('created_at', { mode: 'date', withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp('updated_at', { mode: 'date', withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => ({
    workspaceStatusIdx: index('outreach_drafts_ws_status_idx').on(
      table.workspaceId,
      table.status,
    ),
    workspaceProductIdx: index('outreach_drafts_ws_product_idx').on(
      table.workspaceId,
      table.productProfileId,
    ),
    reviewItemProductIdx: index('outreach_drafts_review_product_idx').on(
      table.reviewItemId,
      table.productProfileId,
    ),
    /**
     * At most one *active* draft per (review_item, product). "Active" means
     * any status except `superseded`. We can't express that as a simple
     * unique index, so the service layer enforces it: when generating a new
     * draft for an existing pair, mark prior non-superseded rows as
     * `superseded` in the same transaction.
     */
    activeDraftIdx: uniqueIndex('outreach_drafts_active_idx')
      .on(table.workspaceId, table.reviewItemId, table.productProfileId)
      .where(sql`status <> 'superseded'`),
  }),
);

export type OutreachDraft = typeof outreachDrafts.$inferSelect;
export type NewOutreachDraft = typeof outreachDrafts.$inferInsert;
export type OutreachDraftStatus = (typeof outreachDraftStatus.enumValues)[number];
export type OutreachDraftMethod = 'rules' | 'ai' | 'hybrid';

/**
 * Phase 19: outreach queue. Approved drafts (or one-off scheduled sends)
 * land here with a scheduled_send_at; a BullMQ recurring worker picks
 * them up and dispatches via mail.sendMessage.
 *
 * status flow:
 *   queued    — waiting for scheduled_send_at to elapse
 *   sending   — worker has claimed and started the send
 *   sent      — provider returned a messageId
 *   failed    — provider error; last_error populated
 *   skipped   — domain cooldown / daily cap / suppression blocked send
 *   cancelled — operator cancelled before send
 */
export const outreachQueueStatus = pgEnum('outreach_queue_status', [
  'queued',
  'sending',
  'sent',
  'failed',
  'skipped',
  'cancelled',
]);

export const sendDelayMode = pgEnum('send_delay_mode', [
  'immediate',
  'fixed',
  'random',
]);

export const outreachQueue = pgTable(
  'outreach_queue',
  {
    id: bigserial('id', { mode: 'bigint' }).primaryKey(),
    workspaceId: bigint('workspace_id', { mode: 'bigint' })
      .notNull()
      .references(() => workspaces.id, { onDelete: 'cascade' }),
    /** Which mailbox to send from. */
    mailboxId: bigint('mailbox_id', { mode: 'bigint' }).notNull(),
    /** Source draft (when the queue item was created from outreach_drafts). */
    draftId: bigint('draft_id', { mode: 'bigint' }).references(
      () => outreachDrafts.id,
      { onDelete: 'set null' },
    ),
    /** Recipient as a flat array — copied off the draft / supplied by caller. */
    toAddresses: text('to_addresses').array().notNull().default(sql`'{}'::text[]`),
    ccAddresses: text('cc_addresses').array().notNull().default(sql`'{}'::text[]`),
    bccAddresses: text('bcc_addresses').array().notNull().default(sql`'{}'::text[]`),
    subject: text('subject').notNull(),
    bodyText: text('body_text'),
    bodyHtml: text('body_html'),
    /** Optional thread anchor for replies (preserved through to send). */
    inReplyTo: text('in_reply_to'),
    references: text('references').array().notNull().default(sql`'{}'::text[]`),

    status: outreachQueueStatus('status').notNull().default('queued'),
    /** Mode used to compute scheduled_send_at. */
    delayMode: sendDelayMode('delay_mode').notNull().default('immediate'),
    /** Computed at enqueue time. */
    scheduledSendAt: timestamp('scheduled_send_at', {
      mode: 'date',
      withTimezone: true,
    })
      .notNull()
      .defaultNow(),

    attemptCount: smallint('attempt_count').notNull().default(0),
    lastError: text('last_error'),
    /** mail_message id once sent. */
    sentMessageId: bigint('sent_message_id', { mode: 'bigint' }),

    createdBy: text('created_by').references(() => users.id, {
      onDelete: 'set null',
    }),
    createdAt: timestamp('created_at', { mode: 'date', withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp('updated_at', { mode: 'date', withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => ({
    workspaceStatusIdx: index('outreach_queue_ws_status_idx').on(
      table.workspaceId,
      table.status,
    ),
    workspaceScheduleIdx: index('outreach_queue_ws_schedule_idx').on(
      table.workspaceId,
      table.scheduledSendAt,
    ),
    /** At most one active queue item per draft. */
    draftActiveIdx: uniqueIndex('outreach_queue_draft_active_idx')
      .on(table.draftId)
      .where(sql`status IN ('queued', 'sending')`),
  }),
);

export type OutreachQueueEntry = typeof outreachQueue.$inferSelect;
export type NewOutreachQueueEntry = typeof outreachQueue.$inferInsert;
export type OutreachQueueStatus = (typeof outreachQueueStatus.enumValues)[number];
export type SendDelayMode = (typeof sendDelayMode.enumValues)[number];

/**
 * Phase 19: per-workspace send-queue settings. Daily cap + delay mode
 * defaults + domain cooldown live here.
 */
export const outreachSendSettings = pgTable('outreach_send_settings', {
  workspaceId: bigint('workspace_id', { mode: 'bigint' })
    .primaryKey()
    .references(() => workspaces.id, { onDelete: 'cascade' }),
  dailyEmailLimit: smallint('daily_email_limit').notNull().default(50),
  /** Hours between consecutive emails to the same domain. */
  domainCooldownHours: smallint('domain_cooldown_hours').notNull().default(24),
  defaultDelayMode: sendDelayMode('default_delay_mode').notNull().default('random'),
  fixedDelayMinutes: smallint('fixed_delay_minutes').notNull().default(15),
  randomDelayMinMinutes: smallint('random_delay_min_minutes').notNull().default(5),
  randomDelayMaxMinutes: smallint('random_delay_max_minutes').notNull().default(30),
  emergencyPause: boolean('emergency_pause').notNull().default(false),
  updatedBy: text('updated_by').references(() => users.id, { onDelete: 'set null' }),
  updatedAt: timestamp('updated_at', { mode: 'date', withTimezone: true })
    .notNull()
    .defaultNow(),
});

export type OutreachSendSettings = typeof outreachSendSettings.$inferSelect;
export type NewOutreachSendSettings = typeof outreachSendSettings.$inferInsert;

/**
 * Phase A: per-thread conversation state. Created when the first
 * outbound for a (qualified_lead, mail_thread) pair lands. Updated
 * by the reply pipeline on every inbound. One row per conversation.
 *
 * If the lead is referred to a new contact, the handoff opens a NEW
 * thread → a NEW row here, while the original row is closed with
 * `closed_reason='handed_off'` and `referral_to_email` set.
 */
export const outreachThreadState = pgTable(
  'outreach_thread_state',
  {
    id: bigserial('id', { mode: 'bigint' }).primaryKey(),
    workspaceId: bigint('workspace_id', { mode: 'bigint' })
      .notNull()
      .references(() => workspaces.id, { onDelete: 'cascade' }),
    /** Lead this conversation belongs to. Multi-product threads share
     *  the same lead row — see qualified_leads dedupe rules. */
    qualifiedLeadId: bigint('qualified_lead_id', { mode: 'bigint' }).notNull(),
    /** mail_threads.id — the email thread this state is tracking. */
    threadId: bigint('thread_id', { mode: 'bigint' }).notNull(),
    /** Where the conversation currently sits. Mirrors outreach_stage. */
    stage: outreachStage('stage').notNull().default('discovery'),
    /** Last AI verdict on the most recent inbound message. */
    lastInboundIntent: text('last_inbound_intent'),
    /** Last AI confidence on that verdict, 0-100. */
    lastInboundConfidence: smallint('last_inbound_confidence'),
    lastInboundAt: timestamp('last_inbound_at', {
      mode: 'date',
      withTimezone: true,
    }),
    lastOutboundAt: timestamp('last_outbound_at', {
      mode: 'date',
      withTimezone: true,
    }),
    /** Closed when the conversation reaches a terminal state. */
    closedAt: timestamp('closed_at', { mode: 'date', withTimezone: true }),
    /** Why the conversation closed: `handed_off`, `not_interested`,
     *  `no_reply`, `qualified`, `error`. Free-form text for forward
     *  compat; we don't enum it. */
    closedReason: text('closed_reason'),
    /** If closed_reason='handed_off', the email we forked to. */
    referralToEmail: text('referral_to_email'),
    /** Foreign-key style pointer to the new thread state, if any. */
    referralToThreadStateId: bigint('referral_to_thread_state_id', {
      mode: 'bigint',
    }),

    createdAt: timestamp('created_at', { mode: 'date', withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp('updated_at', { mode: 'date', withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => ({
    /** One state row per (workspace, thread) — a thread can carry
     *  multiple products for the same lead but only one conversation. */
    threadKey: uniqueIndex('outreach_thread_state_thread_idx').on(
      table.workspaceId,
      table.threadId,
    ),
    leadIdx: index('outreach_thread_state_lead_idx').on(
      table.workspaceId,
      table.qualifiedLeadId,
    ),
    openIdx: index('outreach_thread_state_open_idx')
      .on(table.workspaceId, table.stage)
      .where(sql`closed_at IS NULL`),
  }),
);

export type OutreachThreadState = typeof outreachThreadState.$inferSelect;
export type NewOutreachThreadState = typeof outreachThreadState.$inferInsert;
