import { sql } from 'drizzle-orm';
import {
  bigint,
  bigserial,
  index,
  jsonb,
  pgEnum,
  pgTable,
  smallint,
  text,
  timestamp,
  uniqueIndex,
} from 'drizzle-orm/pg-core';
import { users } from './auth';
import { workspaces } from './workspaces';
import { sourceRecords } from './connectors';
import { productProfiles } from './products';
import { reviewItems } from './review';
import { qualifications } from './qualifications';

/**
 * Lifecycle of an outreach draft:
 *
 *   draft       ← freshly generated by the engine, awaiting human review
 *   needs_edit  ← reviewer flagged it for edits but not approved/rejected
 *   approved    ← reviewer signed off; ready for the future Send phase
 *   rejected    ← reviewer rejected; reason captured
 *   superseded  ← a newer draft for the same (review_item, product) replaced
 *                 this one; kept for audit but not surfaced in the queue
 *
 * Phase 8 does NOT send anything — the lifecycle stops at `approved`.
 * The Send phase (later) will read approved drafts and dispatch.
 */
export const outreachDraftStatus = pgEnum('outreach_draft_status', [
  'draft',
  'needs_edit',
  'approved',
  'rejected',
  'superseded',
]);

/**
 * One outreach draft per (review_item, product_profile) attempt. A new
 * draft for the same pair supersedes the previous one — we keep the row
 * but mark it `superseded` so the audit trail is preserved.
 *
 * `method` is the audit trail of how this draft was produced:
 *   - rules: deterministic templates from product profile + lessons
 *   - ai:    AI provider generation
 *   - hybrid: rules-first scaffold, AI fills body
 */
export const outreachDrafts = pgTable(
  'outreach_drafts',
  {
    id: bigserial('id', { mode: 'bigint' }).primaryKey(),
    workspaceId: bigint('workspace_id', { mode: 'bigint' })
      .notNull()
      .references(() => workspaces.id, { onDelete: 'cascade' }),

    // Source linkage. A draft is for a specific review_item and product.
    // We also denormalize sourceRecordId + qualificationId so the draft
    // table can be queried without traversing review_items.
    reviewItemId: bigint('review_item_id', { mode: 'bigint' })
      .notNull()
      .references(() => reviewItems.id, { onDelete: 'cascade' }),
    sourceRecordId: bigint('source_record_id', { mode: 'bigint' })
      .notNull()
      .references(() => sourceRecords.id, { onDelete: 'cascade' }),
    productProfileId: bigint('product_profile_id', { mode: 'bigint' })
      .notNull()
      .references(() => productProfiles.id, { onDelete: 'cascade' }),
    qualificationId: bigint('qualification_id', { mode: 'bigint' }).references(
      () => qualifications.id,
      { onDelete: 'set null' },
    ),

    status: outreachDraftStatus('status').notNull().default('draft'),

    // ---- generated content ----
    channel: text('channel').notNull().default('email'),
    language: text('language').notNull().default('en'),
    subject: text('subject'),
    body: text('body').notNull(),
    /** 0..100. Engine self-confidence in the draft. */
    confidence: smallint('confidence').notNull().default(50),

    // ---- generation audit ----
    method: text('method').notNull(), // 'rules' | 'ai' | 'hybrid'
    model: text('model'),
    /** Prompt fragments + lesson IDs + product field snapshots used. */
    evidence: jsonb('evidence').notNull().default(sql`'{}'::jsonb`),
    /** Forbidden phrases that the engine REMOVED before persisting (audit). */
    forbiddenStripped: text('forbidden_stripped')
      .array()
      .notNull()
      .default(sql`'{}'::text[]`),
    /** Lesson IDs whose rule text influenced this draft. */
    matchedLessonIds: bigint('matched_lesson_ids', { mode: 'bigint' })
      .array()
      .notNull()
      .default(sql`'{}'::bigint[]`),

    // ---- review trail ----
    rejectionReason: text('rejection_reason'),
    approvedByUserId: text('approved_by_user_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    approvedAt: timestamp('approved_at', { mode: 'date', withTimezone: true }),
    rejectedByUserId: text('rejected_by_user_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    rejectedAt: timestamp('rejected_at', { mode: 'date', withTimezone: true }),
    editedByUserId: text('edited_by_user_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    editedAt: timestamp('edited_at', { mode: 'date', withTimezone: true }),

    createdBy: text('created_by').references(() => users.id, {
      onDelete: 'set null',
    }),
    createdAt: timestamp('created_at', { mode: 'date', withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp('updated_at', { mode: 'date', withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => ({
    workspaceStatusIdx: index('outreach_drafts_ws_status_idx').on(
      table.workspaceId,
      table.status,
    ),
    workspaceProductIdx: index('outreach_drafts_ws_product_idx').on(
      table.workspaceId,
      table.productProfileId,
    ),
    reviewItemProductIdx: index('outreach_drafts_review_product_idx').on(
      table.reviewItemId,
      table.productProfileId,
    ),
    /**
     * At most one *active* draft per (review_item, product). "Active" means
     * any status except `superseded`. We can't express that as a simple
     * unique index, so the service layer enforces it: when generating a new
     * draft for an existing pair, mark prior non-superseded rows as
     * `superseded` in the same transaction.
     */
    activeDraftIdx: uniqueIndex('outreach_drafts_active_idx')
      .on(table.workspaceId, table.reviewItemId, table.productProfileId)
      .where(sql`status <> 'superseded'`),
  }),
);

export type OutreachDraft = typeof outreachDrafts.$inferSelect;
export type NewOutreachDraft = typeof outreachDrafts.$inferInsert;
export type OutreachDraftStatus = (typeof outreachDraftStatus.enumValues)[number];
export type OutreachDraftMethod = 'rules' | 'ai' | 'hybrid';
