// docs/USER_GUIDE.md, generated (AP-03): the handbook the in-app guide
// reads, in Markdown for people, followed by the full route table from the
// navigation registry. `pnpm handbook:export` writes it, and
// src/tests/assistant-handbook.test.ts fails while the committed file
// differs from renderUserGuide(), so the docs cannot drift from the app.
//
// The output never depends on the machine it runs on: the billing block
// describes the default catalogue (documentedBillingFacts), not one
// install's environment.

import { routeTable, type RouteTableRow } from '@/lib/nav/route-table';
import { documentedBillingFacts } from './generated';
import { buildHandbookSource, handbookVersion, stripClaimTags } from './index';

/** Where the export writes, relative to the repository root. */
export const USER_GUIDE_PATH = 'docs/USER_GUIDE.md';

function areaPath(r: RouteTableRow): string {
  if (r.placement === 'menu') return `Account menu › ${r.areaLabel}`;
  return r.groupHeading ? `${r.groupHeading} › ${r.areaLabel}` : r.areaLabel;
}

function who(r: RouteTableRow): string {
  if (r.superAdminOnly) return 'super-admins';
  if (r.capability === 'admin') return 'owners and admins';
  if (r.capability === 'write') return 'members and up';
  return 'everyone';
}

/** Every page the registry knows, as a Markdown table. */
export function routeTableMarkdown(rows: ReadonlyArray<RouteTableRow> = routeTable()): string {
  const lines = [
    '## Route table',
    '',
    'Every page of the app, in navigation order (generated from `src/lib/nav/registry.ts`).',
    '',
    '| Area | Page | Path | For | Who |',
    '| --- | --- | --- | --- | --- |',
  ];
  for (const r of rows) {
    const page = r.section ? `${r.section} › ${r.label}` : r.label;
    lines.push(
      `| ${areaPath(r)} | ${page} | \`${r.href ?? r.pattern}\` | ${r.purpose} | ${who(r)} |`,
    );
  }
  return lines.join('\n');
}

export function renderUserGuide(): string {
  const source = stripClaimTags(buildHandbookSource({ billing: documentedBillingFacts() }));
  // In-app links read as code in a document that is not served by the app.
  const body = source.replace(/\[(\/[^\]\s]*)\]/g, '`$1`');
  return [
    `<!-- Generated by \`pnpm handbook:export\` from src/lib/assistant/handbook (${handbookVersion(source)}). Do not edit by hand: change the handbook or the navigation registry, then run the export again. -->`,
    '',
    body,
    '',
    routeTableMarkdown(),
    '',
  ].join('\n');
}
